language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

after_success:
  - curl https://stainless-steel.github.io/travis/documentation.sh | bash;

env:
  global:
    - secure: vZkiTOKMtYP6/Acz2DtADr5MoKMH/pIiIKRPELLuDU6KIOOoMKDDXITV0sriXxcyY1yxIevUbdSsH1SK4wMzXzRq702RqF8+gRY2DdPtVWge4AojB7I8sS9WHK7EzIs14guE/4WuqisAMj24rRE67/+Q8UKDfM1lAdGZ6w/HocY=

notifications:
  email: false

addons:
  apt:
    packages:
      - gfortran
