language: rust

before_install:
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install cmake
  - sudo apt-get install gfortran

after_success:
  - curl https://stainless-steel.github.io/travis/after_success.sh | bash

env:
  global:
    secure: YQg8W+5ZsiC+5VKQrDzrKvrt0D5sB7qT1Trf6AxgyVEjXCLhVBN98trys0/PicEqATTl9LUgW5K/N7fgkniuDavt6shPL2g/bAoxn+ZFMv8vIGGcv/6AYC8t78H1nar86k4rlA25lLjdx/BPsOd7sxJxeL76nOFA1warT6A4+XQ=

notifications:
  email: false
