[package]
name = "libblas-sys"
version = "0.0.21"
authors = ["Corey Richardson <corey@octayn.net>", "Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/libblas-sys"
homepage = "https://github.com/stainless-steel/libblas-sys"
documentation = "https://stainless-steel.github.io/libblas-sys"
description = "The package provides bindings to the Basic Linear Algebra Subprograms."

[dependencies]
libc = "*"

[features]
default = ["openblas"]
openblas = ["openblas-provider"]
netlib = ["netlib-provider"]

[dependencies.openblas-provider]
version = "*"
optional = true

[dependencies.netlib-provider]
version = "*"
optional = true
