[package]
name = "libblas-sys"
version = "0.0.12"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/libblas-sys"
homepage = "https://github.com/stainless-steel/libblas-sys"
documentation = "https://stainless-steel.github.io/libblas-sys"
description = "The package facilitates static linking with the Basic Linear Algebra Subprograms."
links = "libblas"
build = "build.rs"

[dependencies]
libc = "*"
